services:
  backend:
    build: ./backend
    container_name: express
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on: []

  frontend:
    build: ./frontend
    container_name: react
    ports:
      - "8080:8080"
    depends_on:
      - backend
