
services:
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: express
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: react
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    depends_on:
      - backend

