name: CI - Tests

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
    tags:
      - 'release-candidate-*'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: "Europe/Madrid"  # Forzamos la zona horaria a España

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm run test
