name: Build and Push Docker Image

on:
  # release:
  #   types: [published]
  [workflow_dispatch]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to DockerHub
        run: |
          docker login -u alexrguez9 -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image frontend
        run: |
          docker build -t alexrguez9/deportes_urjc:frontend-${{ github.ref.replace('/', '-') }} .
          docker tag deportesurjc-frontend alexrguez9/deportes_urjc:frontend-${{ github.ref.replace('/', '-') }}
          docker push alexrguez9/deportes_urjc:frontend-${{ github.ref.replace('/', '-') }}

      - name: Build and push Docker image backend
        run: |
          docker build -t alexrguez9/deportes_urjc:backend-${{ github.ref.replace('/', '-') }} .
          docker tag deportesurjc-backend alexrguez9/deportes_urjc:backend-${{ github.ref.replace('/', '-') }}
          docker push alexrguez9/deportes_urjc:backend-${{ github.ref.replace('/', '-') }}
