name: Build and Push Docker Image

on:
  # release:
  #   types: [published]
  [workflow_dispatch]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to DockerHub
        run: |
          docker login -u alexrguez9 -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get branch name
        id: get_branch
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | sed 's/\//-/g')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Build and tag frontend image
        run: |
          docker build -t alexrguez9/deportes_urjc:frontend-${{ env.BRANCH_NAME }} ./path-to-frontend
          docker tag deportesurjc-frontend alexrguez9/deportes_urjc:frontend-${{ github.ref.replace('/', '-') }}
          docker push alexrguez9/deportes_urjc:frontend-${{ env.BRANCH_NAME }}

      - name: Build and tag backend image
        run: |
          docker build -t alexrguez9/deportes_urjc:backend-${{ env.BRANCH_NAME }} ./path-to-backend
          docker tag deportesurjc-backend alexrguez9/deportes_urjc:backend-${{ github.ref.replace('/', '-') }}
          docker push alexrguez9/deportes_urjc:backend-${{ env.BRANCH_NAME }}