name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:  # Ejecuta el workflow cuando se abra o actualice un PR
  workflow_dispatch:  # Permite ejecución manual del workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./frontend # Cambia al directorio 'frontend'
        run: npm install

      - name: Run tests
        working-directory: ./frontend # Cambia al directorio 'frontend'
        run: npm run test

  build-and-push:
    needs: test  # Asegura que el job de tests pase antes de ejecutar este
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to DockerHub
        run: |
          docker login -u alexrguez9 -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image frontend
        run: |
          ref=${GITHUB_REF#refs/*/}
          sanitized_ref=$(echo "$ref" | sed 's/\//-/g')
          echo "BRANCH_OR_TAG_NAME=$sanitized_ref" >> $GITHUB_ENV

      - name: Build and tag frontend image
        run: |
          docker build -t alexrguez9/deportes_urjc:frontend-${{ env.BRANCH_OR_TAG_NAME }} ./frontend
          docker push alexrguez9/deportes_urjc:frontend-${{ env.BRANCH_OR_TAG_NAME }}

      - name: Build and push Docker image backend
        run: |
          docker build -t alexrguez9/deportes_urjc:backend-${{ env.BRANCH_OR_TAG_NAME }} ./backend
          docker push alexrguez9/deportes_urjc:backend-${{ env.BRANCH_OR_TAG_NAME }}
